# -*- coding: utf-8 -*-
"""空污

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBsf3eR_k2FMcn3figoGNXRgCWFDHcxS
"""

import csv
import urllib.request

URL = (
    'https://data.moenv.gov.tw/api/v2/aqx_p_432'
    '?api_key=e75b1660-e564-4107-aad5-a8be1f905dd9'
    '&limit=1000&sort=ImportDate%20desc&format=CSV'
)

AQI_LEVELS = [
    (50,  "良好",           "💚", "AQI 0-50，空氣品質良好"),
    (100, "普通",           "💛", "AQI 51-100，敏感族群請注意"),
    (150, "對敏感族群不健康", "🟠", "AQI 101-150，敏感族群應減少戶外活動"),
    (200, "對所有族群不健康", "🔴", "AQI 151-200，一般民眾應減少戶外活動"),
    (300, "非常不健康",      "🟣", "AQI 201-300，應避免戶外活動"),
    (500, "危險",           "🟤", "AQI 301+，請留在室內並緊閉門窗"),
]

def get_aqi_info(aqi_str):
    """根據 AQI 數值回傳 (圖示, 等級, 說明)"""
    try:
        aqi = int(aqi_str)
    except ValueError:
        return "❓", "未知", "無法解析 AQI 數值"
    for threshold, label, icon, desc in AQI_LEVELS:
        if aqi <= threshold:
            return icon, label, desc
    return "🟤", "危險", "AQI 極高，請留在室內"

def fetch_data(url):
    """下載並解析 CSV 資料，回傳 list（跳過標題列）"""
    with urllib.request.urlopen(url) as response:
        content = response.read().decode('utf-8')
    rows = list(csv.reader(content.splitlines()))
    return rows[1:]

def search_station(data, keyword):
    """搜尋符合關鍵字的測站，回傳結果列表"""
    return [row for row in data if keyword in row[0]]

def display_station(row):
    """格式化輸出單一測站資訊（含 AQI 等級）"""
    aqi_icon, aqi_label, aqi_desc = get_aqi_info(row[2])
    print(f"""
┌─────────────────────────────────────────
│ 測站：{row[0]}　　縣市：{row[1]}
│ 污染物：{row[3]}　　時間：{row[16]}
├─────────────────────────────────────────
│ AQI：{row[2]}　{aqi_icon} {aqi_label}
│ {aqi_desc}
│ 狀態：{row[4]}
└─────────────────────────────────────────""")

def print_aqi_legend():
    """列印 AQI 等級說明"""
    print("\n【AQI 等級說明】")
    for _, label, icon, desc in AQI_LEVELS:
        print(f"  {icon}  {label}：{desc}")
    print()

def main():
    print("正在載入空氣品質資料...")
    try:
        data = fetch_data(URL)
    except Exception as e:
        print(f"資料載入失敗：{e}")
        return

    print_aqi_legend()

    while True:
        keyword = input("請輸入查詢測站名稱（輸入 q 離開）：").strip()
        if keyword.lower() == 'q':
            break
        if not keyword:
            print("請輸入測站名稱。\n")
            continue

        results = search_station(data, keyword)
        if results:
            print(f"\n共找到 {len(results)} 筆資料：")
            for row in results:
                display_station(row)
            print()
        else:
            print("找不到該測站資料，請確認名稱是否正確。\n")

    input("\n按下 Enter 鍵結束程式...")

if __name__ == "__main__":
    main()